Add the old system tab and new options
AVMG20/controlpanel pull request #20
Opened 2022-11-06 21:32 UTC by Ferks-FK

This PR adds the new options of version 8.x [PR](https://github.com/ControlPanel-gg/dashboard/pull/595).
And other simple fixes.

Added:
- [x] Add new System tab.
- [x] Add the option to block common users from creating new servers.
- [x] Add the option to block the creation of new user accounts.

Todo:
- [ ] Make blocking new user accounts actually work.

Additional context:
I have no idea if I made the new seeders correctly, let me know about it xD

2022-11-07 07:10 UTC, AVMG20 requested changes
I'm curious why you didn't add your settings to the general settings? Looks good so far. Minor feedback. The settings don't actually work yet so please change your PR to a Draft since now it seems this is ready to merge. Great job 👍

2022-11-07 07:10 UTC, AVMG20 commented on resources/views/livewire/checkout.blade.php
> +        @if(!$creation_of_new_servers && Auth::user()->roles->get(0)->id === 1)
You can not check for roles. Ppl may delete and add back roles and the role ids may update

2022-11-07 07:10 UTC, AVMG20 commented on database/seeders/Standard/NewOptionsSeeder.php
> +        DB::table('settings')->insert([
1 do not use a seeder for the settings. Check the settings docs
2. Everytime this seeder is ran which is everytime the panel updates. You add the same few rows. Causing errors

2022-11-07 07:10 UTC, AVMG20 commented on database/settings/2022_11_05_174207_remove_register_ip_check.php
> +    }
You removed something from general which in this pr is fine. But since the panel is not live its fine to just update the existing migration :)

2022-11-07 07:10 UTC, AVMG20 commented on resources/views/settings/system.blade.php
> +                    name="creation_of_new_users"
Label. Allow creation of new users. Or. Allow register 
Makes the setting a bit clearer without reading the tooltip

2022-11-07 07:10 UTC, AVMG20 commented on resources/views/settings/system.blade.php
> +                <x-input.checkbox label="{{(__('Creation of new servers'))}}"
Same as above

2022-11-09 12:23 UTC, 1day2die commented
wait why is this to be merged in "develop" branch

2022-11-09 12:25 UTC, 1day2die commented
dunno why we need systemsettings. i wouldve put in in the general settings. its the same IMO

2022-11-09 12:33 UTC, AGuyNamedJens commented
> wait why is this to be merged in "develop" branch

No idea, i'll set it to the main branch for Ferks

2023-05-11 13:24 UTC, closed without merging